// NewsDecodedAI — High-Quality Curated Demo Data
// Used for initial database seeding and fallback data layer

import type { NewsArticle } from "./news";
import { todayEditionDate } from "./dates";

const today = todayEditionDate();

export const DEMO_ARTICLES: NewsArticle[] = [
  // --- AI & TECHNOLOGY ---
  {
    id: "art-ai-01",
    title: "Breakthrough in Autonomous Neuromorphic Computing Slashes AI Training Energy by 80%",
    slug: "breakthrough-neuromorphic-computing-slashes-ai-energy",
    summary: "Researchers deploy photonics-integrated neuromorphic silicon that mirrors biological synaptic plasticity, achieving frontier-level inference at a fraction of traditional datacenter power.",
    content: "A landmark collaboration between leading semiconductor consortia and university research labs has demonstrated the first wafer-scale photonic neuromorphic accelerator. Operating at sub-milliwatt power envelopes, the new architecture executes complex transformer models with zero thermal throttling, fundamentally challenging the energy constraints of global AI infrastructure.",
    category: "ai-tech",
    subcategory: "Semiconductors & AI",
    sourceName: "Tech Intelligence Daily",
    sourceUrl: "https://example.com/neuromorphic-breakthrough",
    imageUrl: null,
    impactScore: 94,
    importanceScore: 96,
    sentiment: "positive",
    whatHappened: "A joint international consortium unveiled a photonic-neuromorphic processor capable of running multi-billion parameter reasoning models with an 80% reduction in power consumption compared to modern GPUs.",
    whyItMatters: "Datacenter energy demands have threatened to bottleneck the expansion of artificial intelligence. Drastically cutting energy requirements prevents grid destabilization and democratizes local edge AI compute.",
    whoIsAffected: "Hyperscale cloud providers, semiconductor manufacturers, clean energy grids, enterprise AI developers, and hardware startups.",
    whatHappensNext: "Commercial test units are scheduled for foundry tape-out in Q3, with pilot datacenter integration testing planned over the next 18 months.",
    futureImpact: "Could accelerate the rollout of self-contained embodied robotics and onboard aerospace computing without requiring multi-kilowatt power supplies.",
    tags: ["Artificial Intelligence", "Semiconductors", "Clean Tech", "Hardware", "Neuromorphic"],
    keyEntities: ["Photonic Labs", "Global Foundry Alliance", "IEEE Standards Committee"],
    readTime: 4,
    isBreaking: true,
    isFeatured: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    saved: false,
  },
  {
    id: "art-ai-02",
    title: "Frontier Foundation Models Achieve Verified Mathematical Proof Synthesis",
    slug: "frontier-foundation-models-mathematical-proof-synthesis",
    summary: "New formal reasoning architecture solves previously open combinatorial math conjectures with end-to-end formal verification in Lean.",
    content: "Advanced recursive reasoning frameworks paired with formal theorem provers have generated verified mathematical solutions to longstanding geometry and number theory problems. Unlike probabilistic token generation, the system validates every deductive leap through formal proof assistants.",
    category: "ai-tech",
    subcategory: "Artificial General Intelligence",
    sourceName: "Frontier AI Review",
    sourceUrl: "https://example.com/math-proof-synthesis",
    imageUrl: null,
    impactScore: 88,
    importanceScore: 91,
    sentiment: "positive",
    whatHappened: "Next-generation reasoning systems achieved 100% formal proof verification on graduate-level Olympiad and published mathematical problems without human intervention.",
    whyItMatters: "Proves that AI systems can generate rigorous, verifiable deductive logic rather than merely generating plausible-sounding hallucinations.",
    whoIsAffected: "Academic mathematicians, software verification engineers, aerospace safety auditors, and cryptographic protocol designers.",
    whatHappensNext: "Research teams are extending the formal verification loop into hardware synthesis and zero-defect aerospace firmware generation.",
    futureImpact: "May automate software vulnerability auditing and accelerate discoveries in quantum physics and material sciences.",
    tags: ["Artificial Intelligence", "Formal Verification", "Mathematics", "Software Engineering"],
    keyEntities: ["Lean Prover Community", "Institute for Advanced Studies"],
    readTime: 5,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    saved: false,
  },
  {
    id: "art-ai-03",
    title: "Global Open-Weight AI Alliance Standardizes Decentralized Model Governance",
    slug: "open-weight-ai-alliance-decentralized-governance",
    summary: "Leading tech organizations and open-source foundations ratify international safety standards for open-weights, ensuring transparency and safety.",
    content: "Over forty international technology organizations, research institutions, and open-source groups have signed the Open Model Compact, establishing benchmarked safety audits and cryptographic watermarking for open-source AI systems.",
    category: "ai-tech",
    subcategory: "Policy & Open Source",
    sourceName: "Open Source Chronicle",
    sourceUrl: "https://example.com/open-weight-compact",
    imageUrl: null,
    impactScore: 82,
    importanceScore: 85,
    sentiment: "neutral",
    whatHappened: "Tech leaders signed a collective charter establishing standardized red-teaming protocols and provenance tracking for open-weight foundation models.",
    whyItMatters: "Protects open innovation while addressing legislative concerns over catastrophic risk and misuse.",
    whoIsAffected: "Open-source developers, academic researchers, startup founders, and global regulatory bodies.",
    whatHappensNext: "The first shared red-teaming datasets and benchmark evaluation suites will be published across public registries.",
    futureImpact: "Prevents regulatory capture while fostering a resilient, decentralized ecosystem of specialized small models.",
    tags: ["Open Source", "AI Governance", "Cybersecurity", "Policy"],
    keyEntities: ["Linux Foundation", "Open AI Alliance", "European AI Office"],
    readTime: 3,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    saved: false,
  },

  // --- WORLD NEWS ---
  {
    id: "art-world-01",
    title: "Global Clean Energy Grid Pact Ratified by 48 Nations to Connect Transcontinental Solar Corridors",
    slug: "global-clean-energy-grid-pact-transcontinental-corridors",
    summary: "Historic accord commits $320 billion toward high-voltage direct current (HVDC) subsea cables linking solar-rich deserts with industrial demand centers across three continents.",
    content: "At the Geneva International Climate & Infrastructure Summit, delegates from 48 countries finalized the Trans-Equatorial Grid Treaty. The landmark initiative establishes standardized regulatory frameworks and funding mechanisms for intercontinental HVDC interconnections, transferring diurnal solar surplus between hemispheres.",
    category: "world",
    subcategory: "International Treaties",
    sourceName: "Global Diplomat",
    sourceUrl: "https://example.com/clean-energy-pact",
    imageUrl: null,
    impactScore: 96,
    importanceScore: 98,
    sentiment: "positive",
    whatHappened: "48 nations formalized a multilateral infrastructure treaty allocating $320B for transcontinental HVDC power lines to balance global renewable supply and demand around the clock.",
    whyItMatters: "Resolves the intermittency problem of solar and wind by transferring power from sunlit timezones to nighttime peak consumption regions across the globe.",
    whoIsAffected: "Global energy utilities, infrastructure funds, industrial manufacturers, and emerging economies in the global solar belt.",
    whatHappensNext: "Engineering teams will break ground on the first 3,400km subsea cable linking North Africa and Southern Europe early next year.",
    futureImpact: "Could eliminate baseline dependence on fossil-fuel peaker plants across participating countries by 2035.",
    tags: ["Global Economy", "Renewable Energy", "Geopolitics", "Infrastructure", "Climate Action"],
    keyEntities: ["UN Infrastructure Commission", "International Renewable Energy Agency", "World Bank"],
    readTime: 5,
    isBreaking: true,
    isFeatured: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    saved: false,
  },
  {
    id: "art-world-02",
    title: "Pacific Maritime Trade Corridor Modernization Slashes Cross-Ocean Transit Times",
    slug: "pacific-maritime-trade-corridor-modernization",
    summary: "Automated port hubs, green methanol shipping fleets, and digitized customs protocols reduce cargo delays across major shipping lanes by 40%.",
    content: "A coordinated modernization program across twelve major Pacific ports has achieved record throughput efficiency. Autonomous electric container cranes, smart logistics tracking, and expedited green corridors have normalized maritime supply chains following years of post-pandemic friction.",
    category: "world",
    subcategory: "Trade & Logistics",
    sourceName: "Maritime Executive",
    sourceUrl: "https://example.com/pacific-trade-corridor",
    imageUrl: null,
    impactScore: 84,
    importanceScore: 86,
    sentiment: "positive",
    whatHappened: "A synchronized automated logistics framework deployed across Pacific hub ports cut maritime transit friction and container dwelling times by over 40%.",
    whyItMatters: "Lower logistics friction directly decreases the landed cost of consumer goods, raw materials, and precision electronics worldwide.",
    whoIsAffected: "Exporters, freight forwarders, global retailers, and manufacturing supply chains.",
    whatHappensNext: "Port authorities plan to expand automated zero-emission berth corridors to Atlantic trading hubs next quarter.",
    futureImpact: "Accelerates international commerce velocity while reducing maritime sector greenhouse emissions.",
    tags: ["Global Economy", "Logistics", "Trade", "Supply Chains"],
    keyEntities: ["International Maritime Organization", "Pacific Port Authorities Consortium"],
    readTime: 4,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    saved: false,
  },
  {
    id: "art-world-03",
    title: "International Space Treaty Updated for Commercial Orbital Debris Removal",
    slug: "international-space-treaty-commercial-debris-removal",
    summary: "New legal frameworks clear private aerospace companies to safely capture and de-orbit legacy rocket stages from low Earth orbit.",
    content: "United Nations aerospace delegates have reached unanimous consensus on amendments to the Outer Space Treaty, establishing legal liability protections and salvage compensation structures for active orbital debris cleanup missions.",
    category: "world",
    subcategory: "Aerospace Governance",
    sourceName: "Space Commerce Weekly",
    sourceUrl: "https://example.com/space-debris-treaty",
    imageUrl: null,
    impactScore: 81,
    importanceScore: 83,
    sentiment: "positive",
    whatHappened: "UN member states ratified a revised space governance framework authorizing commercial robotic tugs to remove abandoned satellites and rocket bodies.",
    whyItMatters: "Guards against the Kessler Syndrome cascade of orbital collisions that could paralyze global GPS, telecommunications, and earth observation satellites.",
    whoIsAffected: "Commercial satellite operators, space launch providers, aerospace insurers, and defense agencies.",
    whatHappensNext: "Five licensed orbital removal missions are slated for test rendezvous in low Earth orbit over the next 12 months.",
    futureImpact: "Preserves sustainable satellite orbits for future broadband constellations and space exploration.",
    tags: ["Space Exploration", "Aerospace", "Geopolitics", "International Law"],
    keyEntities: ["UN Committee on the Peaceful Uses of Outer Space", "ESA", "NASA"],
    readTime: 4,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    saved: false,
  },

  // --- BUSINESS ---
  {
    id: "art-biz-01",
    title: "Global Central Banks Signal Coordinated Liquidity Shift as Inflation Settles at 2.0% Target",
    slug: "global-central-banks-coordinated-liquidity-shift",
    summary: "Key monetary authorities outline predictable easing roadmap, unlocking $1.4 trillion in pent-up corporate capital expenditures and private credit expansion.",
    content: "Following synchronized policy meetings in Basel, central bankers affirmed that underlying core inflation has stabilized across key developed economies. The consensus statement outlines a gradual, data-dependent normalization of benchmark borrowing costs, providing long-term visibility for commercial lending markets.",
    category: "business",
    subcategory: "Monetary Policy & Macro",
    sourceName: "Financial Times Digest",
    sourceUrl: "https://example.com/central-banks-easing",
    imageUrl: null,
    impactScore: 92,
    importanceScore: 95,
    sentiment: "positive",
    whatHappened: "Major central banking authorities issued joint guidance projecting steady rate reductions and liquidity normalization over the next four quarters.",
    whyItMatters: "Lowers corporate debt refinancing costs and unlocks long-delayed infrastructure and capital expenditure investments.",
    whoIsAffected: "Commercial banks, mortgage lenders, corporate CFOs, private equity syndicates, and real estate developers.",
    whatHappensNext: "Commercial banks are recalibrating corporate credit terms and issuance schedules in anticipation of the easing cycle.",
    futureImpact: "Stimulates global mergers & acquisitions activity and venture capital deployment into deep tech infrastructure.",
    tags: ["Global Economy", "Monetary Policy", "Banking", "Corporate Finance"],
    keyEntities: ["Bank for International Settlements", "Federal Reserve", "European Central Bank"],
    readTime: 4,
    isBreaking: true,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    saved: false,
  },
  {
    id: "art-biz-02",
    title: "Solid-State Battery Consortium Begins High-Volume Automotive Deliveries",
    slug: "solid-state-battery-consortium-automotive-deliveries",
    summary: "Next-generation ceramic-electrolyte cells achieve 900 km range per charge and 12-minute 80% recharge cycles under real-world vehicle testing.",
    content: "An international consortium of automotive manufacturers and battery chemists has initiated commercial deliveries of solid-state lithium-metal cells. The breakthrough battery packs deliver 450 Wh/kg energy density with zero thermal runaway risk under rigorous puncture and impact tests.",
    category: "business",
    subcategory: "Automotive & Energy",
    sourceName: "Automotive Intelligence",
    sourceUrl: "https://example.com/solid-state-deliveries",
    imageUrl: null,
    impactScore: 89,
    importanceScore: 92,
    sentiment: "positive",
    whatHappened: "Commercial-scale production lines started rolling out solid-state automotive battery packs with double the energy density of conventional lithium-ion cells.",
    whyItMatters: "Eliminates EV range anxiety, accelerates price parity with internal combustion vehicles, and vastly improves battery safety.",
    whoIsAffected: "Electric vehicle manufacturers, mineral refiners, charging network operators, and consumer motorists.",
    whatHappensNext: "Tier-1 automakers will debut consumer production vehicles powered by the new cells at upcoming international motor shows.",
    futureImpact: "Could accelerate global automotive fleet electrification by 3-5 years ahead of current policy targets.",
    tags: ["Electric Vehicles", "Clean Tech", "Automotive", "Manufacturing"],
    keyEntities: ["Solid Power Consortium", "Global Auto Manufacturers Alliance"],
    readTime: 4,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    saved: false,
  },
  {
    id: "art-biz-03",
    title: "Quantum Sensing Deployed in Commercial Aircraft Navigation and Geological Exploration",
    slug: "quantum-sensing-commercial-aircraft-geological-exploration",
    summary: "Miniaturized atomic gyroscopes and gravimeters provide unjammable GPS-independent navigation and deep subterranean mineral mapping.",
    content: "Aviation safety regulators have certified the first commercial inertial quantum navigation system for long-haul civil airliners. Measuring quantum state changes in laser-cooled rubidium atoms, the self-contained units provide millimeter-accurate positioning without satellite signals.",
    category: "business",
    subcategory: "Deep Tech & Aerospace",
    sourceName: "DeepTech Review",
    sourceUrl: "https://example.com/quantum-sensing-commercial",
    imageUrl: null,
    impactScore: 85,
    importanceScore: 88,
    sentiment: "positive",
    whatHappened: "Civil aviation authorities approved quantum-inertial navigation pods that remain fully accurate during satellite jamming or geomagnetic storms.",
    whyItMatters: "Protects commercial air travel from GPS spoofing and jamming attacks while enabling zero-footprint mineral and groundwater exploration.",
    whoIsAffected: "Airlines, defense contractors, mining explorers, and maritime navigation crews.",
    whatHappensNext: "Commercial airlines will begin retrofitting international wide-body fleets during scheduled maintenance cycles.",
    futureImpact: "Guarantees absolute positioning autonomy for unmanned cargo ships, subsea submersibles, and commercial airliners.",
    tags: ["Quantum Computing", "Aerospace", "Cybersecurity", "Deep Tech"],
    keyEntities: ["Civil Aviation Authority", "Quantum Sensing Lab", "Airbus"],
    readTime: 4,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    saved: false,
  },

  // --- POLITICS ---
  {
    id: "art-pol-01",
    title: "Bipartisan Digital Privacy and Algorithm Transparency Act Signed into Law",
    slug: "bipartisan-digital-privacy-algorithm-transparency-act",
    summary: "Landmark legislation guarantees citizen ownership of biometric data, mandates algorithmic explainability for credit and employment, and bans dark pattern design.",
    content: "In a rare show of unified bipartisan consensus, lawmakers enacted the comprehensive Digital Privacy and Algorithmic Rights Act. The statute establishes clear legal liability for deceptive data harvesting, enforces data portability, and mandates third-party safety audits on algorithmic ranking systems.",
    category: "politics",
    subcategory: "Legislation & Rights",
    sourceName: "Capitol Policy Review",
    sourceUrl: "https://example.com/digital-privacy-act",
    imageUrl: null,
    impactScore: 91,
    importanceScore: 94,
    sentiment: "positive",
    whatHappened: "Comprehensive digital privacy and algorithmic transparency regulations were enacted with strong consumer data protection standards.",
    whyItMatters: "Establishes clear, enforceable federal guidelines for AI data privacy, algorithmic accountability, and consumer protection.",
    whoIsAffected: "Social platforms, advertising networks, financial tech lenders, HR software vendors, and consumers.",
    whatHappensNext: "Regulatory commissions will issue detailed technical compliance guidelines and certification frameworks over the next 180 days.",
    futureImpact: "Reshapes the digital advertising ecosystem toward privacy-preserving cryptography and verifiable on-device analytics.",
    tags: ["Policy", "Cybersecurity", "Artificial Intelligence", "Consumer Rights"],
    keyEntities: ["Federal Trade Commission", "Congressional Privacy Caucus", "Electronic Frontier Foundation"],
    readTime: 5,
    isBreaking: true,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    saved: false,
  },
  {
    id: "art-pol-02",
    title: "Global Treaty on Autonomous Cyber Defense Protocol Harmonization Established",
    slug: "global-treaty-autonomous-cyber-defense-harmonization",
    summary: "International cybersecurity pact creates joint rapid-response mechanism against state-sponsored critical infrastructure ransomware.",
    content: "Ministers of Homeland Security and Digital Governance from thirty nations signed the Cyber Defense Harmonization Agreement. The treaty creates automated, cryptographic threat-sharing channels to neutralize zero-day exploits targeting electrical grids, hospitals, and water purification facilities.",
    category: "politics",
    subcategory: "Cybersecurity & Geopolitics",
    sourceName: "Defense & Policy Journal",
    sourceUrl: "https://example.com/cyber-defense-treaty",
    imageUrl: null,
    impactScore: 86,
    importanceScore: 89,
    sentiment: "positive",
    whatHappened: "Thirty nations established a coordinated cyber defense protocol and joint telemetry sharing network to safeguard civilian infrastructure.",
    whyItMatters: "Critical infrastructure attacks have escalated in sophistication; coordinated defense minimizes single-point vulnerabilities and downtime.",
    whoIsAffected: "Public utilities, national cybersecurity agencies, cloud hosting providers, and critical infrastructure operators.",
    whatHappensNext: "The Joint Cyber Response Center will conduct quarterly simulated grid defense exercises starting next month.",
    futureImpact: "Significantly raises the barrier of entry and diplomatic cost for hostile state-sponsored cyber operations.",
    tags: ["Cybersecurity", "Geopolitics", "Policy", "Infrastructure"],
    keyEntities: ["CISA", "ENISA", "Interpol Cyber Directorate"],
    readTime: 4,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    saved: false,
  },

  // --- MARKETS ---
  {
    id: "art-mkt-01",
    title: "Global Clean Energy Index Hits Record High as Green Bond Issuance Surpasses $1.8 Trillion",
    slug: "global-clean-energy-index-record-green-bonds",
    summary: "Surging institutional capital flows into carbon-neutral utility projects and geothermal grids drive renewable equities to historic highs.",
    content: "Institutional asset managers and sovereign wealth funds poured record allocations into the S&P Global Clean Energy Index this quarter. Yield-seeking pension capital combined with government matching subsidies drove green debt issuance past $1.8 trillion year-to-date.",
    category: "markets",
    subcategory: "Equities & Bonds",
    sourceName: "Wall Street Intelligence",
    sourceUrl: "https://example.com/clean-energy-index-record",
    imageUrl: null,
    impactScore: 87,
    importanceScore: 90,
    sentiment: "positive",
    whatHappened: "Clean energy equities and green infrastructure bonds reached record capital inflow volumes, outperforming traditional commodities.",
    whyItMatters: "Substantial capital abundance lowers the cost of equity for renewable developers, accelerating physical project completion times.",
    whoIsAffected: "Institutional fund managers, green bond issuers, utility operators, and retail investors.",
    whatHappensNext: "Sovereign wealth funds are expanding direct co-investment facilities for grid-scale battery storage and transmission links.",
    futureImpact: "Locks in multi-decade low-cost capital for global renewable grid expansion.",
    tags: ["Markets", "Renewable Energy", "Global Economy", "Green Finance"],
    keyEntities: ["S&P Dow Jones Indices", "BloombergNEF", "Global Green Bond Council"],
    readTime: 4,
    isBreaking: false,
    isFeatured: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    saved: false,
  },
  {
    id: "art-mkt-02",
    title: "Decentralized Real-World Asset (RWA) Tokenization Volume Crosses $50 Billion Milestone",
    slug: "decentralized-real-world-asset-tokenization-50-billion",
    summary: "Tokenized treasury bills, institutional private credit, and commercial trade finance on public blockchains experience exponential adoption.",
    content: "On-chain financial analytics confirm that tokenized Real-World Assets (RWAs) have surpassed $50 billion in total value locked. Major investment banks and institutional asset managers are utilizing compliance-gated smart contracts for instantaneous, 24/7 cross-border settlement of institutional credit.",
    category: "markets",
    subcategory: "Digital Assets & Crypto",
    sourceName: "Crypto Markets Weekly",
    sourceUrl: "https://example.com/rwa-tokenization-milestone",
    imageUrl: null,
    impactScore: 83,
    importanceScore: 87,
    sentiment: "positive",
    whatHappened: "Institutional tokenization of real-world financial assets crossed $50 billion across major audited smart contract networks.",
    whyItMatters: "Enables instant 24/7 liquidity, eliminates T+2 settlement risk, and drastically reduces intermediary administrative fees.",
    whoIsAffected: "Institutional asset managers, corporate treasurers, DeFi protocols, and custodian banks.",
    whatHappensNext: "Tier-1 investment banks are preparing tokenized repo facilities and cross-border commercial paper issuance programs.",
    futureImpact: "Bridges traditional capital markets with cryptographic settlement layers for frictionless global finance.",
    tags: ["Cryptocurrency", "Markets", "Fintech", "Banking"],
    keyEntities: ["BlackRock BUIDL Fund", "Ondo Finance", "Securitize"],
    readTime: 4,
    isBreaking: false,
    isFeatured: false,
    publishedAt: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    saved: false,
  },
];
